## 2、Numpy简介
### 1. Numpy的数组中，元素数据类型必须统一
    * 要么都是整型，要么都是浮点型，要么都是字符串型，不能同时出现多种数据
### 2. Numpy数组创建的4种方式
    * np.array创建
    * np.random创建
    * np.arange创建
    * np特殊函数创建

In [1]:
import numpy as np

In [2]:
# 1 使用np.array从list创建数组
a = np.array([1, 2, 3, 4])
print(a)
print(type(a))

[1 2 3 4]
<class 'numpy.ndarray'>


In [3]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', '

In [4]:
# 2 使用np.arange创建数组
b=np.arange(10)
print(b)

[0 1 2 3 4 5 6 7 8 9]


In [5]:
help(np.arange)

Help on built-in function arange in module numpy:

arange(...)
    arange([start,] stop[, step,], dtype=None, *, like=None)
    
    Return evenly spaced values within a given interval.
    
    Values are generated within the half-open interval ``[start, stop)``
    (in other words, the interval including `start` but excluding `stop`).
    For integer arguments the function is equivalent to the Python built-in
    `range` function, but returns an ndarray rather than a list.
    
    When using a non-integer step, such as 0.1, it is often better to use
    `numpy.linspace`. See the warnings section below for more information.
    
    Parameters
    ----------
    start : integer or real, optional
        Start of interval.  The interval includes this value.  The default
        start value is 0.
    stop : integer or real
        End of interval.  The interval does not include this value, except
        in some cases where `step` is not an integer and floating point
        round-off 

In [15]:
# 3 使用np.random创建数组
## 3.1 np.random.random(N, M)创建一个N行M列的随机数组，每个元素都是0-1之间的小数
c1 = np.random.random((2,3))
print(c1)
## 3.2 np.random.randint(i, j, size=(N, M))创建一个N行M列的随机数组，每个元素都是i-j之间的整数
c2 = np.random.randint(0,9,size=(4,4))
print(c2)

[[0.80791478 0.16532928 0.12177298]
 [0.25832448 0.39922027 0.25780706]]
[[4 4 0 7]
 [3 5 6 4]
 [0 8 8 5]
 [6 0 6 2]]


In [14]:
# 4 使用np创建特殊数组
## 4.1 np.zeros((N, M))创建一个N行M列的随机数组，每个元素都是0
e1=np.zeros((3, 2))
print(e1)
## 4.2 np.ones((N, M))创建一个N行M列的随机数组，每个元素都是1
e2=np.ones((3, 2))
print(e2)
## 4.3 np.full((N, M), k)创建一个N行M列的随机数组，每个元素都是k
e3=np.full((3, 2), 8)
print(e3)
## 4.4 np.eye(N)创建一个N阶单位矩阵
e4=np.eye(3)
print(e4)

[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[8 8]
 [8 8]
 [8 8]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
