# 3、Numpy数组数据类型dtype

In [1]:
import numpy as np

In [2]:
# 查看数组数据类型
a = np.arange(9)
print(a)
print(a.dtype)

[0 1 2 3 4 5 6 7 8]
int64


In [14]:
# 指定数据类型创建数组
## 整型（以int8为例）
b = np.array([1,2,3,4,5], dtype=np.int8)
print(b)
print(b.dtype)
## 浮点型（以float16为例）
c = np.array([1,2,3,4,5], dtype=np.float16)
print(c)
print(c.dtype)
## Object类型
class Person:
    def __init__(self, name, age):
        self.name = name
        self.age = age
d = np.array([Person("小王", 13), Person("小张", 15)])
print(d)
print(d.dtype)
## 字符串类型（相当于python中的byte型，有编码）
f = np.array(['a', 'b'], dtype="S") #也写成 f = np.array(['a', 'b'], dtype=np.string_)
print(f)
print(f.dtype)
## Unicode类型(未编码)
e = np.array(['a', 'b'], dtype="U")#也写成 f = np.array(['a', 'b'], dtype=np.unicode_)
print(e)
print(e.dtype)

[1 2 3 4 5]
int8
[1. 2. 3. 4. 5.]
float16
object
[b'a' b'b']
|S1
['a' 'b']
<U1


In [16]:
# 类型转换-.astype
uf = f.astype("U")
print(uf)
print(uf.dtype)
print(f.dtype)

['a' 'b']
<U1
|S1
