In [1]:
import numpy as np

In [3]:
# 创建多维数组
a1=np.array([1,2,3])
print(a1.ndim) # 查看数组a1维度
print(a1.shape) # 查看数组a1具体形状
a2 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(a2.ndim) # 查看数组a2维度
print(a2.shape)# 查看数组a2具体形状
a3 = np.array([
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [7,8,9],
        [10,11,12]
    ]
])
print(a3.ndim) # 查看数组a3维度
print(a3.shape) # 查看数组a3具体形状

1
(3,)
2
(2, 3)
3
(2, 2, 3)


In [7]:
# 改变数组形状
a4 = a3.reshape((2,6))
print(a4)
print(a4.ndim)
print(a4.shape)
a5 = a3.reshape((12,))
# a5 = a3.flatten() 通常用法，直接扁平化
print(a5)
print(a5.ndim)
print(a5.shape)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
2
(2, 6)
[ 1  2  3  4  5  6  7  8  9 10 11 12]
1
(12,)


In [14]:
# size-数组元素的个数
# itemsize-数组中元素所占字节大小

print("a3.size表示a3中有{}个数组元素".format(a3.size))
print("a3.itemsize表示a3中每个元素所占{}个字节的内存".format(a3.itemsize))
print(a3.dtype)
print("a3.size * a3.itemsize表示a3总共占用了{}个字节的内存".format(a3.size * a3.itemsize))

a3.size表示a3中有12个数组元素
a3.itemsize表示a3中每个元素所占8个字节的内存
int64
a3.size * a3.itemsize表示a3总共占用了96个字节的内存
