In [1]:
import numpy as np

1. 布尔索引通过相同数组元素位置上的布尔值来提取元素
2. 逻辑条件可以是多个，有逻辑与(&)和逻辑或(|)连接
3. 多条件中，每个条件要使用小括号

In [6]:
a1 = np.arange(20).reshape((4, 5))  # 创建元素为0到19的整数数组，并设置shape为4行5列
print(a1)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [7]:
print(a1 < 10)  # 对数组a1做逻辑运算，得到布尔索引

[[ True  True  True  True  True]
 [ True  True  True  True  True]
 [False False False False False]
 [False False False False False]]


In [8]:
print(a1[a1 < 10])  # 用布尔索引从数组中取得对应的元素

[0 1 2 3 4 5 6 7 8 9]


In [10]:
print(a1[(a1 < 5) | (a1 > 10)]) # 两个条件的例子

[ 0  1  2  3  4 11 12 13 14 15 16 17 18 19]
