In [1]:
import numpy as np

1. 使用直接索引和切片来替换
2. 使用布尔索引来替换
3. 使用where函数来替换

In [4]:
a1=np.random.randint(0,# 使用布尔索引进行元素替换
a1[a1<5] = 3
print(a1)10,size=(3,5)) # 构造3行5列的数组，元素为0到9之 间的随机整数
print(a1)

[[5 7 2 6 6]
 [1 7 3 8 4]
 [6 5 6 0 5]]


In [5]:
# 通过直接索引进行元素替换
a1[1]=0 # 把第1列所有元素都替换成0
print(a1)

[[5 7 2 6 6]
 [0 0 0 0 0]
 [6 5 6 0 5]]


In [6]:
a1[1]=np.array([1,2,3,4,5]) 把第1列换成[1 2 3 4 5]
print(a1)

[[5 7 2 6 6]
 [1 2 3 4 5]
 [6 5 6 0 5]]


In [7]:
# 使用布尔索引进行元素替换
a1[a1<5] = 3
print(a1)

[[5 7 3 6 6]
 [3 3 3 3 5]
 [6 5 6 3 5]]


In [9]:
# 使用where函数进行元素替换
print(np.where(a1<5,0,1)) # 指定判断条件为小于5，如果小于5就替换0，否则替换为1

[[1 1 0 1 1]
 [0 0 0 0 1]
 [1 1 1 0 1]]
