In [1]:
import numpy as np

1. 数组可以和数字直接进行运算
2. 两个shape相同的数组可以进行运算
3. 两个shape不同的数组要计算则需要满足广播机制
    1. 两个数组从末尾算起的维度的轴长度相同或者其中一方的长度为1，则认为它们是广播兼容的。
    2. 广播会在缺失和长度为1的的维度上进行。

In [2]:
# 数组与数的运算
a1 = np.random.randint(0, 5, size=(4, 6))  # 随机生成4行6列的数组a1，其中元素为0到4直接的整数
print("a1:\n{}".format(a1))
print("=" * 20)
print("a1 * 2: \n{}".format(a1 * 2))  # 让a1中所有元素的值都翻一倍

a1:
[[1 3 3 0 1 0]
 [2 0 2 0 1 3]
 [3 0 3 2 1 0]
 [3 2 4 2 3 1]]
a1 * 2: 
[[2 6 6 0 2 0]
 [4 0 4 0 2 6]
 [6 0 6 4 2 0]
 [6 4 8 4 6 2]]


In [3]:
# 数组与数组的运算
# shape相同的数组之间的运算
a2 = np.random.randint(0, 5, size=(4, 6))  # 随机生成4行6列的数组a2，其中元素为0到4直接的整数
print("a2:\n{}".format(a2))
print("=" * 20)
print("a1:\n{}".format(a1))
print("=" * 20)
print("a1 + a2:\n{}".format(a1 + a2))  # 采用广播机制，让a1与a2对应位置相加

a2:
[[2 2 1 4 4 3]
 [0 3 3 4 0 3]
 [1 1 0 0 4 4]
 [2 0 1 3 0 0]]
a1:
[[1 3 3 0 1 0]
 [2 0 2 0 1 3]
 [3 0 3 2 1 0]
 [3 2 4 2 3 1]]
a1 + a2:
[[3 5 4 4 5 3]
 [2 3 5 4 1 6]
 [4 1 3 2 5 4]
 [5 2 5 5 3 1]]


In [4]:
# shape不同的数组之间的运算
a3 = np.random.randint(0, 5, size=(4, 5))  # 随机生成4行5列的数组a3，其中元素为0到4直接的整数
print("a3:\n{}".format(a3))
print("=" * 20)
print("a2:\n{}".format(a2))
print("=" * 20)
print("a2 + a3:\n{}".format(a2 + a3))  # 两个结构不同个数组不能运用广播机制进行运算

a3:
[[2 1 4 4 1]
 [3 2 1 4 1]
 [1 4 2 0 3]
 [3 2 3 1 3]]
a2:
[[2 2 1 4 4 3]
 [0 3 3 4 0 3]
 [1 1 0 0 4 4]
 [2 0 1 3 0 0]]


ValueError: operands could not be broadcast together with shapes (4,6) (4,5) 

In [7]:
a4 = np.random.randint(0, 5, size=(4, 1))  # 随机生成4行1列的数组a4，其中元素为0到4直接的整数
print("a1:\n{}".format(a1))
print("=" * 20)
print("a4:\n{}".format(a4))
print("=" * 20)
print("a1 + a4:\n{}".format(a1 + a4))  # 采用广播机制，让a4与a1中每一列对应位置相加

a1:
[[1 3 3 0 1 0]
 [2 0 2 0 1 3]
 [3 0 3 2 1 0]
 [3 2 4 2 3 1]]
a4:
[[2]
 [0]
 [4]
 [2]]
a1 + a4:
[[3 5 5 2 3 2]
 [2 0 2 0 1 3]
 [7 4 7 6 5 4]
 [5 4 6 4 5 3]]


In [8]:
a5 = np.random.randint(0, 5, size=(1, 6))  # 随机生成1行6列的数组a5，其中元素为0到4直接的整数
print("a1:\n{}".format(a1))
print("=" * 20)
print("a5:\n{}".format(a5))
print("=" * 20)
print("a1 + a5:\n{}".format(a1 + a5))  # 采用广播机制，让a5与a1中每一行对应位置相加

a1:
[[1 3 3 0 1 0]
 [2 0 2 0 1 3]
 [3 0 3 2 1 0]
 [3 2 4 2 3 1]]
a5:
[[3 0 0 2 4 2]]
a1 + a5:
[[4 3 3 2 5 2]
 [5 0 2 2 5 5]
 [6 0 3 4 5 2]
 [6 2 4 4 7 3]]
