In [1]:
import numpy as np

1. reshape和resize都是重新定义数组形状
    1. reshape不会修改数组本身，只返回修改后的结果
    2. resize会直接修改数组本身
2. flatten和ravel都是将数组降为一维数组，且都不会直接修改原数组
    1. flatten返回的是原数组的copy，操作返回值不影响原数组
    2. ravel返回的是原数组的view，操作返回值会影响原数组

In [2]:
# reshape操作不会改变原数组
a1 = np.random.randint(0, 10, size=(3, 4)) # 创建3行4列的数组a1，其中元素为0到9之间的随机整数
print("a1:\n{}".format(a1))
print("=" * 20)
print("a1.reshape(2,6):\n{}".format(a1.reshape(2,6))) # 对a1进行reshape操作，返回新shape的数组
print("=" * 20)
print("a1:\n{}".format(a1)) # reshape操作不会改变原数组a1的shape

a1:
[[9 7 9 5]
 [2 6 8 7]
 [6 6 4 7]]
a1.reshape(2,6):
[[9 7 9 5 2 6]
 [8 7 6 6 4 7]]
a1:
[[9 7 9 5]
 [2 6 8 7]
 [6 6 4 7]]


In [3]:
# resize操作会改变原数组
a2 = np.random.randint(0, 10, size=(3, 4)) # 创建3行4列的数组a2，其中元素为0到9之间的随机整数
print("a2:\n{}".format(a2))
print("=" * 20)
a2.resize(2,6) # 对a2进行resize操作，没有返回值
print("=" * 20)
print("a2:\n{}".format(a2)) # reshape操作改变了原数组a2的shape

a2:
[[3 0 9 6]
 [1 2 9 6]
 [6 7 0 7]]
a2:
[[3 0 9 6 1 2]
 [9 6 6 7 0 7]]


In [5]:
# flatten操作不会改变原数组，仅返回一份原数组的一维copy
a3 = np.random.randint(0, 10, size=(3, 4)) # 创建3行4列的数组a3，其中元素为0到9之间的随机整数
print("a3:\n{}".format(a3))
print("=" * 20)
a4=a3.flatten() # 对a3进行flatten操作，返回值赋给a4
print("a4:\n{}".format(a4))
print("=" * 20)
a4[0] = 100 # 修改a4第0个位置的值
print("a4:\n{}".format(a4))
print("=" * 20)
print("a3:\n{}".format(a3)) # 原数组没有变化

a3:
[[9 9 0 2]
 [9 9 9 8]
 [6 4 4 6]]
a4:
[9 9 0 2 9 9 9 8 6 4 4 6]
a4:
[100   9   0   2   9   9   9   8   6   4   4   6]
a3:
[[9 9 0 2]
 [9 9 9 8]
 [6 4 4 6]]


In [6]:
# ravel操作不会改变原数组，返回一份原数组的一维view
a5 = np.random.randint(0, 10, size=(3, 4)) # 创建3行4列的数组a5，其中元素为0到9之间的随机整数
print("a5:\n{}".format(a5))
print("=" * 20)
a6=a5.ravel() # 对a5进行ravel操作，返回值赋给a6
print("a6:\n{}".format(a6))
print("=" * 20)
a6[0] = 100 # 修改a6第0个位置的值
print("a6:\n{}".format(a6))
print("=" * 20)
print("a5:\n{}".format(a5)) # 原数组改变了

a5:
[[4 4 4 1]
 [8 6 9 3]
 [3 7 9 0]]
a6:
[4 4 4 1 8 6 9 3 3 7 9 0]
a6:
[100   4   4   1   8   6   9   3   3   7   9   0]
a5:
[[100   4   4   1]
 [  8   6   9   3]
 [  3   7   9   0]]
