In [1]:
import numpy as np

1. vstack-垂直方向叠加，数组列数必须一致
2. hstack-水平方向叠加，数组行数必须一致
3. concatenate手动指定axis参数来设置具体的叠加方向
    1. axis=0水平方向
    2. axis=1垂直方向
    3. axis=None叠加后转扁平化成1维数组

In [2]:
# 垂直方向的叠加vstack
a1 = np.random.randint(0, 10, size=(3, 5))  # 创建3行5列的数组a1，其中元素为0到9之间的随机整数
print("a1:\n{}".format(a1))
print("=" * 20)
a2 = np.random.randint(0, 10, size=(2, 5))  # 创建2行5列的数组a2，其中元素为0到9之间的随机整数
print("a2:\n{}".format(a2))
print("=" * 20)
a3 = np.vstack([a1, a2])  # 把数组a2垂直叠加到数组a1下面
print("a3=np.vstack([a1,a2]):\n{}".format(a3))

a1:
[[7 5 0 5 6]
 [8 3 7 3 2]
 [9 8 3 4 7]]
a2:
[[3 7 7 4 5]
 [5 0 9 0 6]]
a3=np.vstack([a1,a2]):
[[7 5 0 5 6]
 [8 3 7 3 2]
 [9 8 3 4 7]
 [3 7 7 4 5]
 [5 0 9 0 6]]


In [3]:
# 水平方向的叠加hstack
a4 = np.random.randint(0, 10, size=(3, 5))  # 创建3行5列的数组a4，其中元素为0到9之间的随机整数
print("a4:\n{}".format(a4))
print("=" * 20)
a5 = np.random.randint(0, 10, size=(3, 1))  # 创建3行1列的数组a5，其中元素为0到9之间的随机整数
print("a5:\n{}".format(a5))
print("=" * 20)
a6 = np.hstack([a5, a4])  # 把数组a5叠加到a4前面
print("a6=np.hstack([a5,a4]):\n{}".format(a6))

a4:
[[6 5 2 4 6]
 [4 8 5 7 7]
 [5 8 7 1 0]]
a5:
[[4]
 [9]
 [1]]
a6=np.hstack([a5,a4]):
[[4 6 5 2 4 6]
 [9 4 8 5 7 7]
 [1 5 8 7 1 0]]


In [5]:
# 手动指定叠加方向(垂直)
print("a1:\n{}".format(a1))
print("=" * 20)
print("a2:\n{}".format(a2))
print("=" * 20)
a7 = np.concatenate([a1, a2], axis=0)  # 把数组a2垂直叠加到数组a1下面
print("a7 = np.concatenate([a1,a2], axis=0):\n{}".format(a7))

a1:
[[7 5 0 5 6]
 [8 3 7 3 2]
 [9 8 3 4 7]]
a2:
[[3 7 7 4 5]
 [5 0 9 0 6]]
a7 = np.concatenate([a1,a2], axis=0):
[[7 5 0 5 6]
 [8 3 7 3 2]
 [9 8 3 4 7]
 [3 7 7 4 5]
 [5 0 9 0 6]]


In [6]:
# 手动指定叠加方向(水平)
print("a4:\n{}".format(a4))
print("=" * 20)
print("a5:\n{}".format(a5))
print("=" * 20)
a8 = np.concatenate([a5, a4], axis=1)  # 把数组a5叠加到a4前面
print("a8=np.concatenate([a5,a4], axis=1):\n{}".format(a8))

a4:
[[6 5 2 4 6]
 [4 8 5 7 7]
 [5 8 7 1 0]]
a5:
[[4]
 [9]
 [1]]
a8=np.concatenate([a5,a4], axis=1):
[[4 6 5 2 4 6]
 [9 4 8 5 7 7]
 [1 5 8 7 1 0]]


In [7]:
# 手动指定叠加方向(扁平化)
print("a4:\n{}".format(a4))
print("=" * 20)
print("a5:\n{}".format(a5))
print("=" * 20)
a9 = np.concatenate([a5, a4], axis=None)  # 把数组a5叠加到a4前面
print("a9=np.concatenate([a5,a4], axis=None):\n{}".format(a9))

a4:
[[6 5 2 4 6]
 [4 8 5 7 7]
 [5 8 7 1 0]]
a5:
[[4]
 [9]
 [1]]
a9=np.concatenate([a5,a4], axis=None):
[4 9 1 6 5 2 4 6 4 8 5 7 7 5 8 7 1 0]
