In [1]:
import numpy as np

1. hsplit-水平方向切割，即按列进行切割
    1. 第一种切割方式：直接指定均匀切割成多少列
    2. 第二种切割防止：指定切割列的下标值
2. vsplit-垂直方向切割，即按行进行切割
    1. 第一种切割方式：直接指定均匀切割成多少行
    2. 第二种切割防止：指定切割行的下标值
3. split/array_split-手动指定切割方向（axis=）
    1. axis=0，垂直方向，即按行进行切割
    2. axis=1，水平方向，即按列进行切割

In [3]:
# 水平方向的切割hsplit(按列切割)
a1 = np.random.randint(0, 10, size=(3, 6))  # 创建3行6列的数组a1，其中元素为0到9之间的随机整数
print("a1:\n{}".format(a1))
print("=" * 20)
print("np.hsplit(a1,2):\n{}".format(np.hsplit(a1,2))) # 水平方向均匀切割成2份
print("=" * 20)
print("np.hsplit(a1,(1，2)):\n{}".format(np.hsplit(a1,(1, 2)))) # 水平方向分别从列的第1个位置和第2个位置进行切割

a1:
[[1 1 0 3 9 7]
 [4 3 6 1 1 0]
 [0 5 2 0 4 1]]
np.hsplit(a1,2):
[array([[1, 1, 0],
       [4, 3, 6],
       [0, 5, 2]]), array([[3, 9, 7],
       [1, 1, 0],
       [0, 4, 1]])]
np.hsplit(a1,(1，2)):
[array([[1],
       [4],
       [0]]), array([[1],
       [3],
       [5]]), array([[0, 3, 9, 7],
       [6, 1, 1, 0],
       [2, 0, 4, 1]])]


In [4]:
# 垂直方向的切割vsplit(按行切割)
a2 = np.random.randint(0, 10, size=(6, 3))  # 创建3行6列的数组a1，其中元素为0到9之间的随机整数
print("a2:\n{}".format(a2))
print("=" * 20)
print("np.vsplit(a2,3):\n{}".format(np.vsplit(a2,3))) # 垂直方向均匀切割成3份
print("=" * 20)
print("np.vsplit(a2,(1,4)):\n{}".format(np.vsplit(a2,(1,4)))) # 垂直方向分别从行的第1个位置和第4个位置切割

a2:
[[5 7 0]
 [5 9 9]
 [3 2 8]
 [3 8 1]
 [2 8 8]
 [8 1 8]]
np.vsplit(a2,3):
[array([[5, 7, 0],
       [5, 9, 9]]), array([[3, 2, 8],
       [3, 8, 1]]), array([[2, 8, 8],
       [8, 1, 8]])]
np.vsplit(a2,(1,4)):
[array([[5, 7, 0]]), array([[5, 9, 9],
       [3, 2, 8],
       [3, 8, 1]]), array([[2, 8, 8],
       [8, 1, 8]])]


In [5]:
# 手动指定叠加方向(水平，按列切割)
print("a1:\n{}".format(a1))
print("=" * 20)
print(":\n{}".format(np.split(a1,3,axis=1))) # 水平方向（axis=1）切成均等3份

a1:
[[1 1 0 3 9 7]
 [4 3 6 1 1 0]
 [0 5 2 0 4 1]]
:
[array([[1, 1],
       [4, 3],
       [0, 5]]), array([[0, 3],
       [6, 1],
       [2, 0]]), array([[9, 7],
       [1, 0],
       [4, 1]])]


In [6]:
# 手动指定叠加方向(垂直，按行切割)
print("a2:\n{}".format(a2))
print("=" * 20)
print(":\n{}".format(np.split(a2,3,axis=0))) # 垂直方向（axis=0）切成均等3份

a2:
[[5 7 0]
 [5 9 9]
 [3 2 8]
 [3 8 1]
 [2 8 8]
 [8 1 8]]
:
[array([[5, 7, 0],
       [5, 9, 9]]), array([[3, 2, 8],
       [3, 8, 1]]), array([[2, 8, 8],
       [8, 1, 8]])]
