In [1]:
import numpy as np

1. 通过ndarray.T的形式进行转置
2. 通过ndarray.transpose的形式进行转置
    * 该方法返回的是原数组的View，修改新数组的值会影响原数组

In [3]:
# 使用ndarray的T属性进行转置
t1 = np.random.randint(0, 10, size=(3, 5))  # 创建3行5列的数组t1，其中元素为0到9之间的随机整数
print("t1:\n{}".format(t1))
print("=" * 20)
t1t=t1.T # 获取数组t1的转置
print("t1.T:\n{}".format(t1t)) 
print("=" * 20)
print("t1*t1.T:\n{}".format(t1.dot(t1t))) # 计算t1与其转置的点乘

t1:
[[5 3 3 8 1]
 [3 5 9 3 3]
 [2 2 9 2 1]]
t1.T:
[[5 3 2]
 [3 5 2]
 [3 9 9]
 [8 3 2]
 [1 3 1]]
t1*t1.T:
[[108  84  60]
 [ 84 133 106]
 [ 60 106  94]]


In [9]:
# 使用ndarray的transpose函数进行转置
t3 = np.random.randint(0, 10, size=(3, 5))  # 创建3行5列的数组t3，其中元素为0到9之间的随机整数
print("t3:\n{}".format(t3))
print("=" * 20)
t3t=t3.transpose() # 获取数组t3的转置
print("t3.transpose():\n{}".format(t3t)) 
print("=" * 20)
t3t[0]=100 # 修改t3转置数组的第0个行元素值
print("t3.transpose():\n{}".format(t3t)) 
print("t3:\n{}".format(t3)) # 对应的t3中第0列元素值也改变了

t3:
[[3 0 5 4 0]
 [7 7 6 6 5]
 [2 6 8 6 0]]
t3.transpose():
[[3 7 2]
 [0 7 6]
 [5 6 8]
 [4 6 6]
 [0 5 0]]
t3.transpose():
[[100 100 100]
 [  0   7   6]
 [  5   6   8]
 [  4   6   6]
 [  0   5   0]]
t3:
[[100   0   5   4   0]
 [100   7   6   6   5]
 [100   6   8   6   0]]
