In [1]:
import numpy as np

1. 不拷贝
    * 直接赋值，没有拷贝，仅在stack同区域里为数组定义了不同的名称
2. 浅拷贝
    * 只在stack里开辟了新区域进行拷贝，仍指向原heap空间中的数据
3. 深拷贝
    * 在stack和heap里都开辟里的新区域进行拷贝

In [2]:
# 1. 不拷贝
# 创建以为数组a1，元素为0-9之间的整数
a1 = np.arange(10)
# 把a1直接赋值给a2
a2 = a1
# 查看a2与a1是不是同一个数组对象
print(a2 is a1)

True


In [3]:
# 2. 浅拷贝
# 把a1浅拷贝给a3
a3 = a1.view()
# 查看a3与a1是不是同一个数组对象
print(a3 is a1)
# 修改a3第0个位置的元素值为100
a3[0] = 100
# 查看a1的变化
print(a1)

False
[100   1   2   3   4   5   6   7   8   9]


In [4]:
# 3. 深拷贝
# 把a1深拷贝给a4
a4 = a1.copy()
# 修改a4第1个位置的元素值为200
a4[1] = 200
# 查看a4的变化
print(a4)
# 查看a1的变化
print(a1)

[100 200   2   3   4   5   6   7   8   9]
[100   1   2   3   4   5   6   7   8   9]
