In [2]:
import numpy as np

1. 通用文件操作：保存-savetxt() & 读取-loadtxt()
    1. 一般用于操作类似csv的文本文件
    2. 可以设置header
    3. 不能存储3维以上的数组
2. 专用文件操作：保存-save() & 读取-load()
    1. 一般用于存取非文本类型的文件
    2. 不可设置header
    3. 可以存取3维以上的数组

In [3]:
help(np.savetxt)

Help on function savetxt in module numpy:

savetxt(fname, X, fmt='%.18e', delimiter=' ', newline='\n', header='', footer='', comments='# ', encoding=None)
    Save an array to a text file.
    
    Parameters
    ----------
    fname : filename or file handle
        If the filename ends in ``.gz``, the file is automatically saved in
        compressed gzip format.  `loadtxt` understands gzipped files
        transparently.
    X : 1D or 2D array_like
        Data to be saved to a text file.
    fmt : str or sequence of strs, optional
        A single format (%10.5f), a sequence of formats, or a
        multi-format string, e.g. 'Iteration %d -- %10.5f', in which
        case `delimiter` is ignored. For complex `X`, the legal options
        for `fmt` are:
    
        * a single specifier, `fmt='%.4e'`, resulting in numbers formatted
          like `' (%s+%sj)' % (fmt, fmt)`
        * a full string specifying every real and imaginary part, e.g.
          `' %.4e %+.4ej %.4e %+.4ej %.4

In [4]:
# 创建数组scores，存放20个学生语数英三科的成绩
scores=np.random.randint(0, 100, size=(20, 3))
print("学生成绩：\n{}".format(scores))

学生成绩：
[[68 35 91]
 [18 29 88]
 [80 86 35]
 [25 38  4]
 [91 45 41]
 [61 42 71]
 [55 98 16]
 [21  1 47]
 [37 92 83]
 [17 65 57]
 [35 13 74]
 [ 8 69  8]
 [47 94 61]
 [43 36 22]
 [ 1 87 12]
 [14 46 60]
 [ 6 51 42]
 [72 53 51]
 [42 54 29]
 [68 43 14]]


In [5]:
# 将scores保存为csv文件
np.savetxt("scores.csv", scores, delimiter=",")

In [6]:
# 将scores保存为csv文件，指定header
np.savetxt("scores.csv", scores, delimiter=",", header="语文,数学,英语")

In [8]:
# 将scores保存为csv文件，指定header，设定comments为空字符
np.savetxt("scores.csv", scores, delimiter=",", header="语文,数学,英语", comments="")

In [9]:
# 将scores保存为csv文件，指定header，设定comments为空字符，设定数据的保存格式
np.savetxt("scores.csv", scores, delimiter=",", header="语文,数学,英语", comments="", fmt="%d")

In [10]:
help(np.loadtxt)

Help on function loadtxt in module numpy:

loadtxt(fname, dtype=<class 'float'>, comments='#', delimiter=None, converters=None, skiprows=0, usecols=None, unpack=False, ndmin=0, encoding='bytes', max_rows=None, *, like=None)
    Load data from a text file.
    
    Each row in the text file must have the same number of values.
    
    Parameters
    ----------
    fname : file, str, pathlib.Path, list of str, generator
        File, filename, list, or generator to read.  If the filename
        extension is ``.gz`` or ``.bz2``, the file is first decompressed. Note
        that generators must return bytes or strings. The strings
        in a list or produced by a generator are treated as lines.
    dtype : data-type, optional
        Data-type of the resulting array; default: float.  If this is a
        structured data-type, the resulting array will be 1-dimensional, and
        each row will be interpreted as an element of the array.  In this
        case, the number of columns used 

In [11]:
# 读取scores.csv文件
readScores = np.loadtxt("scores.csv", dtype=np.int, delimiter=",")

/var/folders/59/_lbpck214pqcv3v468n7dv6w0000gn/T/ipykernel_12120/1907374040.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  readScores = np.loadtxt("scores.csv", dtype=np.int, delimiter=",")


ValueError: invalid literal for int() with base 10: '语文'

In [13]:
# 读取scores.csv文件，忽略第1行
readScores = np.loadtxt("scores.csv", dtype=np.int, delimiter=",", skiprows=1)
print(readScores)

[[68 35 91]
 [18 29 88]
 [80 86 35]
 [25 38  4]
 [91 45 41]
 [61 42 71]
 [55 98 16]
 [21  1 47]
 [37 92 83]
 [17 65 57]
 [35 13 74]
 [ 8 69  8]
 [47 94 61]
 [43 36 22]
 [ 1 87 12]
 [14 46 60]
 [ 6 51 42]
 [72 53 51]
 [42 54 29]
 [68 43 14]]


/var/folders/59/_lbpck214pqcv3v468n7dv6w0000gn/T/ipykernel_12120/772440105.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  readScores = np.loadtxt("scores.csv", dtype=np.int, delimiter=",", skiprows=1)


In [16]:
# 以npy格式保存scores到硬盘
np.save("scores", scores)

In [17]:
# 读取scores.npy文件
readNpy = np.load("scores.npy")
print(readNpy)

[[68 35 91]
 [18 29 88]
 [80 86 35]
 [25 38  4]
 [91 45 41]
 [61 42 71]
 [55 98 16]
 [21  1 47]
 [37 92 83]
 [17 65 57]
 [35 13 74]
 [ 8 69  8]
 [47 94 61]
 [43 36 22]
 [ 1 87 12]
 [14 46 60]
 [ 6 51 42]
 [72 53 51]
 [42 54 29]
 [68 43 14]]


In [21]:
# 用savetxt存储三维数组
testArr=np.random.randint(0, 10, size=(4,5,6))
print(testArr)
np.savetxt("test.csv",testArr, delimiter=",")

[[[0 3 1 5 1 5]
  [9 0 6 8 6 8]
  [5 1 1 5 0 4]
  [3 0 0 5 7 3]
  [5 8 9 9 4 3]]

 [[8 6 6 7 2 5]
  [9 5 6 3 4 1]
  [9 4 6 9 6 8]
  [0 0 3 6 9 2]
  [7 2 2 7 3 6]]

 [[1 4 8 3 2 9]
  [4 2 7 2 9 3]
  [2 2 1 9 6 6]
  [9 5 1 1 3 1]
  [6 9 9 9 0 7]]

 [[0 1 0 0 2 8]
  [2 3 5 5 0 0]
  [5 3 8 7 2 4]
  [7 7 4 0 8 8]
  [1 0 5 4 3 7]]]


ValueError: Expected 1D or 2D array, got 3D array instead

In [22]:
# 用save存储三维数组
testArr=np.random.randint(0, 10, size=(4,5,6))
print(testArr)
np.save("test",testArr)

[[[9 7 7 0 5 5]
  [6 8 0 9 7 6]
  [2 6 5 6 2 1]
  [5 8 5 8 8 9]
  [0 7 3 5 3 8]]

 [[0 8 8 4 1 6]
  [5 5 5 1 3 9]
  [6 2 7 8 8 3]
  [9 9 8 9 1 9]
  [4 5 8 7 4 4]]

 [[7 8 8 0 7 3]
  [9 2 2 5 8 2]
  [8 6 1 3 1 0]
  [6 8 2 1 1 0]
  [8 0 9 7 5 8]]

 [[7 4 1 3 3 2]
  [6 9 1 6 7 2]
  [6 8 4 5 0 7]
  [2 2 9 0 2 5]
  [5 7 5 7 5 1]]]
