In [1]:
import numpy as np

# 小结
1. random.seed：设定计算伪随机数的值
2. random.rand：生成随机浮点数/数组
3. random.randn：生成标准正态分布随机数/数组
4. random.randint：生成随机整数/数组
5. random.choice：随机从序列中选取元素
6. random.shuffle：随机打断数组中元素的顺序

In [5]:
# 不设置seed，直接生成随机数
np.random.rand()

0.47179023979832724

In [8]:
# 设置seed，再生成随机数
np.random.seed(1)
np.random.rand()

0.417022004702574

In [18]:
# 生成0-1的随机小数
np.random.rand()

0.4191945144032948

In [24]:
# 生成随机数组
np.random.rand(4, 5)

array([[0.62169572, 0.11474597, 0.94948926, 0.44991213, 0.57838961],
       [0.4081368 , 0.23702698, 0.90337952, 0.57367949, 0.00287033],
       [0.61714491, 0.3266449 , 0.5270581 , 0.8859421 , 0.35726976],
       [0.90853515, 0.62336012, 0.01582124, 0.92943723, 0.69089692]])

In [25]:
# 生成标准正态分布的随机数
np.random.randn()

-0.3992681719195915

In [27]:
# 生成一维数组
data = np.arange(12)
data

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [28]:
# 从data中随机取3个元素
np.random.choice(data, 3)

array([11,  1,  1])

In [29]:
# 从data中随机取元素，组成一个3行4列的数组
np.random.choice(data, size=(3, 4))

array([[ 8,  7,  0, 10],
       [ 3,  4,  2,  0],
       [11,  3,  5,  1]])

In [32]:
# 从0-4中随机取3个元素
np.random.choice(5, 3)

array([3, 0, 1])

In [33]:
# 从0-4中随机取元素，组成一个3行4列的数组
np.random.choice(5, size=(3, 4))

array([[2, 4, 4, 3],
       [3, 3, 3, 2],
       [3, 3, 4, 3]])

In [46]:
# 生成一维数组
data1 = np.arange(10)
data1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
# 打乱data1中元素顺序
np.random.shuffle(data1)
data1

array([5, 7, 3, 0, 4, 1, 6, 9, 8, 2])

In [49]:
# 生成随机整型数组
data2 = np.random.randint(0, 10, size=(5, 6))
data2

array([[0, 6, 7, 0, 3, 9],
       [0, 3, 4, 7, 5, 3],
       [8, 8, 0, 6, 7, 9],
       [5, 4, 9, 5, 2, 5],
       [6, 6, 8, 7, 7, 7]])

In [52]:
# 打乱data2中的行顺序
np.random.shuffle(data2)
data2

array([[5, 4, 9, 5, 2, 5],
       [8, 8, 0, 6, 7, 9],
       [6, 6, 8, 7, 7, 7],
       [0, 3, 4, 7, 5, 3],
       [0, 6, 7, 0, 3, 9]])