In [1]:
import numpy as np

## 小结
1. 最外层括号对应axis=0，依次往里的括号对应axis的取值加1
2. 操作对应的是当前括号下的直接子元素
    1. 如果直接子元素是数，那就是在所有数上的操作
    2. 如果直接子元素是数组，那就是找到对应位置的数上的操作

In [4]:
# 生成二维数组
arr = np.arange(0,4).reshape(2,2)
arr

array([[0, 1],
       [2, 3]])

In [5]:
# axis=0,求和计算
arr.sum(axis=0)

array([2, 4])

In [6]:
# axis=1,求和计算
arr.sum(axis=1)

array([1, 5])

In [9]:
# 生成二维数组
arr1 = np.arange(12).reshape(2,6)
arr1

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [10]:
# 求所有元素的max
arr1.max()

11

In [11]:
# axis=0，做max操作
arr1.max(axis=0)

array([ 6,  7,  8,  9, 10, 11])

In [12]:
# axis=1，做max操作
arr1.max(axis=1)

array([ 5, 11])

In [14]:
# axis=0，做delete操作
np.delete(arr1, 0, axis=0)

array([[ 6,  7,  8,  9, 10, 11]])

In [15]:
# axis=1，做delete操作
np.delete(arr1, 0, axis=1)

array([[ 1,  2,  3,  4,  5],
       [ 7,  8,  9, 10, 11]])

In [16]:
# 生成三维数组
arr2 = np.arange(24).reshape(2,2,6)
arr2

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]],

       [[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]])

In [17]:
# axis=0，做max操作
arr2.max(axis=0)

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])