In [1]:
# 引入Numpy包
import numpy as np

In [2]:
data = np.random.uniform(-20, 20, size=(4, 5))
data

array([[ -2.31184687,   2.92967497,  -1.69130567,  15.73001027,
         14.53253428],
       [ -7.15998078, -15.41770466,  19.87120689,  13.62094683,
         16.52028935],
       [  6.50019617, -14.94476839, -10.89458539,  17.40596821,
         19.85411989],
       [  5.63571719, -16.23753472,  11.6423797 ,  -2.72099872,
          0.70716693]])

## 一元函数

In [3]:
# np.abs：求绝对值
np.abs(data)

array([[ 2.31184687,  2.92967497,  1.69130567, 15.73001027, 14.53253428],
       [ 7.15998078, 15.41770466, 19.87120689, 13.62094683, 16.52028935],
       [ 6.50019617, 14.94476839, 10.89458539, 17.40596821, 19.85411989],
       [ 5.63571719, 16.23753472, 11.6423797 ,  2.72099872,  0.70716693]])

In [4]:
# np.sqrt：开平方根
np.sqrt(data)

/var/folders/59/_lbpck214pqcv3v468n7dv6w0000gn/T/ipykernel_15437/231563697.py:2: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(data)


array([[       nan, 1.71162933,        nan, 3.9661077 , 3.81215612],
       [       nan,        nan, 4.45771319, 3.69065669, 4.06451588],
       [2.54954823,        nan,        nan, 4.17204605, 4.45579621],
       [2.37396655,        nan, 3.41209315,        nan, 0.84093218]])

In [5]:
# np.square：求平方
np.square(data)

array([[  5.34463594,   8.58299542,   2.86051487, 247.43322316,
        211.19455258],
       [ 51.26532481, 237.70561687, 394.86486344, 185.53019246,
        272.91996023],
       [ 42.25255026, 223.34610215, 118.69199087, 302.96772943,
        394.18607677],
       [ 31.76130827, 263.6575339 , 135.54500502,   7.40383403,
          0.50008506]])

In [6]:
# np.exp：求指数
np.exp(data)

array([[9.90780982e-02, 1.87215444e+01, 1.84278760e-01, 6.78354424e+06,
        2.04832774e+06],
       [7.77069486e-04, 2.01454023e-07, 4.26535815e+08, 8.23193714e+05,
        1.49510091e+07],
       [6.65272127e+02, 3.23273091e-07, 1.85584492e-05, 3.62506624e+07,
        4.19309511e+08],
       [2.80259845e+02, 8.87418074e-08, 1.13820702e+05, 6.58089969e-02,
        2.02823697e+00]])

In [7]:
# np.log：求对数
np.log(data)

/var/folders/59/_lbpck214pqcv3v468n7dv6w0000gn/T/ipykernel_15437/1771881011.py:2: RuntimeWarning: invalid value encountered in log
  np.log(data)


array([[        nan,  1.07489148,         nan,  2.75557037,  2.67638988],
       [        nan,         nan,  2.98927179,  2.61160882,  2.80458928],
       [ 1.87183236,         nan,         nan,  2.85681315,  2.98841154],
       [ 1.72912441,         nan,  2.45465186,         nan, -0.34648854]])

In [8]:
# np.sign：数值标签化（大于0变成1，小于0变成-1）
np.sign(data)

array([[-1.,  1., -1.,  1.,  1.],
       [-1., -1.,  1.,  1.,  1.],
       [ 1., -1., -1.,  1.,  1.],
       [ 1., -1.,  1., -1.,  1.]])

In [9]:
# np.ceil：向上取整
np.ceil(data)

array([[ -2.,   3.,  -1.,  16.,  15.],
       [ -7., -15.,  20.,  14.,  17.],
       [  7., -14., -10.,  18.,  20.],
       [  6., -16.,  12.,  -2.,   1.]])

In [10]:
# np.floor：向下取整
np.floor(data)

array([[ -3.,   2.,  -2.,  15.,  14.],
       [ -8., -16.,  19.,  13.,  16.],
       [  6., -15., -11.,  17.,  19.],
       [  5., -17.,  11.,  -3.,   0.]])

In [11]:
# np.rint或者np.round：四舍五入
np.round(data)

array([[ -2.,   3.,  -2.,  16.,  15.],
       [ -7., -15.,  20.,  14.,  17.],
       [  7., -15., -11.,  17.,  20.],
       [  6., -16.,  12.,  -3.,   1.]])

In [12]:
# np.modf：整数部分和小数部分分离
np.modf(data)

(array([[-0.31184687,  0.92967497, -0.69130567,  0.73001027,  0.53253428],
        [-0.15998078, -0.41770466,  0.87120689,  0.62094683,  0.52028935],
        [ 0.50019617, -0.94476839, -0.89458539,  0.40596821,  0.85411989],
        [ 0.63571719, -0.23753472,  0.6423797 , -0.72099872,  0.70716693]]),
 array([[ -2.,   2.,  -1.,  15.,  14.],
        [ -7., -15.,  19.,  13.,  16.],
        [  6., -14., -10.,  17.,  19.],
        [  5., -16.,  11.,  -2.,   0.]]))

## 二元函数

In [13]:
# 加法操作np.add或者运算符+
np.add(data, 1)

array([[ -1.31184687,   3.92967497,  -0.69130567,  16.73001027,
         15.53253428],
       [ -6.15998078, -14.41770466,  20.87120689,  14.62094683,
         17.52028935],
       [  7.50019617, -13.94476839,  -9.89458539,  18.40596821,
         20.85411989],
       [  6.63571719, -15.23753472,  12.6423797 ,  -1.72099872,
          1.70716693]])

In [14]:
# 加法操作np.add或者运算符+
np.add(data, np.random.randint(0, 5, size=(4, 5)))

array([[ -2.31184687,   4.92967497,   1.30869433,  17.73001027,
         14.53253428],
       [ -6.15998078, -14.41770466,  19.87120689,  14.62094683,
         16.52028935],
       [ 10.50019617, -10.94476839, -10.89458539,  17.40596821,
         23.85411989],
       [  7.63571719, -16.23753472,  12.6423797 ,   0.27900128,
          4.70716693]])

In [16]:
# 求data中大于0的数
data[data > 0]

array([ 2.92967497, 15.73001027, 14.53253428, 19.87120689, 13.62094683,
       16.52028935,  6.50019617, 17.40596821, 19.85411989,  5.63571719,
       11.6423797 ,  0.70716693])

In [17]:
# 求data中大于0的数
data[np.greater(data, 0)]

array([ 2.92967497, 15.73001027, 14.53253428, 19.87120689, 13.62094683,
       16.52028935,  6.50019617, 17.40596821, 19.85411989,  5.63571719,
       11.6423797 ,  0.70716693])

In [18]:
# 求data中大于0，小于10的数
data[(data > 0) & (data < 10)]

array([2.92967497, 6.50019617, 5.63571719, 0.70716693])

In [19]:
# 求data中大于0，小于10的数
data[np.logical_and(data > 0, data < 10)]

array([2.92967497, 6.50019617, 5.63571719, 0.70716693])

## 聚合函数

In [21]:
# sum求和
np.sum(data)

73.57148548663861

In [22]:
# sum求和,列求和
np.sum(data, axis=0)

array([  2.66408571, -43.6703328 ,  18.92769553,  44.03592659,
        51.61411045])

In [23]:
# sum求和,行求和
np.sum(data, axis=1)

array([29.18906698, 27.43475763, 17.9209305 , -0.97326963])

In [24]:
# prod求积
np.prod(data)

9.691438632808781e+17

In [25]:
# prod求积,按列求积
np.prod(data, axis=0)

array([   606.38238352, -10960.95624248,   4262.83787928, -10147.58802049,
         3370.78914745])

In [26]:
# prod求积,按行求积
np.prod(data, axis=1)

array([  2618.61090161, 493606.38753325, 365742.29502638,   2050.03521686])

In [27]:
# mean求均值
np.mean(data)

3.6785742743319303

In [29]:
# mean求均值,按列求均值
np.mean(data, axis=0)

array([  0.66602143, -10.9175832 ,   4.73192388,  11.00898165,
        12.90352761])

In [30]:
# mean求均值,按行求均值
np.mean(data, axis=1)

array([ 5.8378134 ,  5.48695153,  3.5841861 , -0.19465393])

In [31]:
# std求标准差
np.std(data)

11.973670952816722

In [32]:
# std求标准差,按列求标准差
np.std(data, axis=0)

array([ 5.67559427,  8.00808586, 11.85746558,  8.03965595,  7.29377432])

In [33]:
# std求标准差,按行求标准差
np.std(data, axis=1)

array([ 7.81044936, 14.08369818, 14.2633271 ,  9.36673172])

In [34]:
# argmin求最小值索引
print(data)
print(np.min(data))
print(np.argmin(data))

[[ -2.31184687   2.92967497  -1.69130567  15.73001027  14.53253428]
 [ -7.15998078 -15.41770466  19.87120689  13.62094683  16.52028935]
 [  6.50019617 -14.94476839 -10.89458539  17.40596821  19.85411989]
 [  5.63571719 -16.23753472  11.6423797   -2.72099872   0.70716693]]
-16.237534723573646
16


In [35]:
# argmin求最小值索引,按列求
print(data)
print(np.min(data, axis=0))
print(np.argmin(data, axis=0))

[[ -2.31184687   2.92967497  -1.69130567  15.73001027  14.53253428]
 [ -7.15998078 -15.41770466  19.87120689  13.62094683  16.52028935]
 [  6.50019617 -14.94476839 -10.89458539  17.40596821  19.85411989]
 [  5.63571719 -16.23753472  11.6423797   -2.72099872   0.70716693]]
[ -7.15998078 -16.23753472 -10.89458539  -2.72099872   0.70716693]
[1 3 2 3 3]


In [39]:
sum(np.arange(1000000))

499999500000

In [40]:
np.sum(np.arange(1000000))

499999500000

## 布尔函数

In [45]:
# 不给条件，any判断是否有元素不等于0
np.any(data)

True

In [46]:
# 不给条件，all判断是否所有元素不等于0
np.all(data)

True

In [49]:
np.any(np.array([0, 0, 0]))

False

In [43]:
# 给条件判断，any判断是否有元素都满足条件
np.any(data > 0)

True

In [42]:
# 给条件判断，all判断是否所有元素都满足条件
np.all(data > 0)

False

In [44]:
np.all(data != 0)

True

In [50]:
# 给条件判断，all判断是否所有元素都满足条件
(data > 0).all()

False

In [51]:
# 给条件判断，any判断是否有元素都满足条件
(data > 0).any()

True

## 排序

In [57]:
# 不指定axis进排序，默认最内层
print(data)
print("=" * 70)
print(np.sort(data))

[[ -2.31184687   2.92967497  -1.69130567  15.73001027  14.53253428]
 [ -7.15998078 -15.41770466  19.87120689  13.62094683  16.52028935]
 [  6.50019617 -14.94476839 -10.89458539  17.40596821  19.85411989]
 [  5.63571719 -16.23753472  11.6423797   -2.72099872   0.70716693]]
[[ -2.31184687  -1.69130567   2.92967497  14.53253428  15.73001027]
 [-15.41770466  -7.15998078  13.62094683  16.52028935  19.87120689]
 [-14.94476839 -10.89458539   6.50019617  17.40596821  19.85411989]
 [-16.23753472  -2.72099872   0.70716693   5.63571719  11.6423797 ]]


In [58]:
# 指定axis=1进排序
print(data)
print("=" * 70)
print(np.sort(data, axis=0))

[[ -2.31184687   2.92967497  -1.69130567  15.73001027  14.53253428]
 [ -7.15998078 -15.41770466  19.87120689  13.62094683  16.52028935]
 [  6.50019617 -14.94476839 -10.89458539  17.40596821  19.85411989]
 [  5.63571719 -16.23753472  11.6423797   -2.72099872   0.70716693]]
[[ -7.15998078 -16.23753472 -10.89458539  -2.72099872   0.70716693]
 [ -2.31184687 -15.41770466  -1.69130567  13.62094683  14.53253428]
 [  5.63571719 -14.94476839  11.6423797   15.73001027  16.52028935]
 [  6.50019617   2.92967497  19.87120689  17.40596821  19.85411989]]


In [60]:
# ndarray.sort进行排序
print(data)
data.sort(axis=0)
print("=" * 70)
print(data)

[[ -2.31184687  -1.69130567   2.92967497  14.53253428  15.73001027]
 [-15.41770466  -7.15998078  13.62094683  16.52028935  19.87120689]
 [-14.94476839 -10.89458539   6.50019617  17.40596821  19.85411989]
 [-16.23753472  -2.72099872   0.70716693   5.63571719  11.6423797 ]]
[[-16.23753472 -10.89458539   0.70716693   5.63571719  11.6423797 ]
 [-15.41770466  -7.15998078   2.92967497  14.53253428  15.73001027]
 [-14.94476839  -2.72099872   6.50019617  16.52028935  19.85411989]
 [ -2.31184687  -1.69130567  13.62094683  17.40596821  19.87120689]]


In [62]:
# argsort排序，返回下标
data2 = np.random.uniform(-20, 20, size=(4, 5))
print(data2)
print(np.argsort(data2))

[[-10.7030199    6.92446262  -4.30791428   8.44456621 -12.65383058]
 [ 15.89937381  15.24068584 -10.11422686 -14.3599904   11.00322691]
 [ 10.98773486  -9.34519594   7.77891522 -14.43639732  13.84193186]
 [ -1.90710347 -18.89960509 -14.88848068  13.79188831  -7.17898173]]
[[4 0 2 1 3]
 [3 2 4 1 0]
 [3 1 2 0 4]
 [1 2 4 0 3]]


In [66]:
# 降序排序
print(data2)
print("=" * 70)
print(-np.sort(-data2))

[[-10.7030199    6.92446262  -4.30791428   8.44456621 -12.65383058]
 [ 15.89937381  15.24068584 -10.11422686 -14.3599904   11.00322691]
 [ 10.98773486  -9.34519594   7.77891522 -14.43639732  13.84193186]
 [ -1.90710347 -18.89960509 -14.88848068  13.79188831  -7.17898173]]
[[  8.44456621   6.92446262  -4.30791428 -10.7030199  -12.65383058]
 [ 15.89937381  15.24068584  11.00322691 -10.11422686 -14.3599904 ]
 [ 13.84193186  10.98773486   7.77891522  -9.34519594 -14.43639732]
 [ 13.79188831  -1.90710347  -7.17898173 -14.88848068 -18.89960509]]


In [69]:
# 降序排序2
print(data2)
print("=" * 70)
index = np.argsort(-data2)
print(np.take(data2, index))

[[-10.7030199    6.92446262  -4.30791428   8.44456621 -12.65383058]
 [ 15.89937381  15.24068584 -10.11422686 -14.3599904   11.00322691]
 [ 10.98773486  -9.34519594   7.77891522 -14.43639732  13.84193186]
 [ -1.90710347 -18.89960509 -14.88848068  13.79188831  -7.17898173]]
[[  8.44456621   6.92446262  -4.30791428 -10.7030199  -12.65383058]
 [-10.7030199    6.92446262 -12.65383058  -4.30791428   8.44456621]
 [-12.65383058 -10.7030199   -4.30791428   6.92446262   8.44456621]
 [  8.44456621 -10.7030199  -12.65383058  -4.30791428   6.92446262]]


## 其他函数

In [75]:
# 测试一下apply_along_axis
def calcMean(x):
    print(x)
    print("=" * 30)


np.apply_along_axis(calcMean, axis=1, arr=data2)

[-10.7030199    6.92446262  -4.30791428   8.44456621 -12.65383058]
[ 15.89937381  15.24068584 -10.11422686 -14.3599904   11.00322691]
[ 10.98773486  -9.34519594   7.77891522 -14.43639732  13.84193186]
[ -1.90710347 -18.89960509 -14.88848068  13.79188831  -7.17898173]


array([None, None, None, None], dtype=object)

In [76]:
# 求一维数组去掉最大值和最小值之后的均值
def calcMean(row):
    print(row)
    newRow = row[np.logical_and(row != row.max(), row != row.min())]
    rowMean = newRow.mean()
    print(rowMean)


np.apply_along_axis(calcMean, axis=1, arr=data2)

[-10.7030199    6.92446262  -4.30791428   8.44456621 -12.65383058]
-2.695490521407637
[ 15.89937381  15.24068584 -10.11422686 -14.3599904   11.00322691]
5.376561964771621
[ 10.98773486  -9.34519594   7.77891522 -14.43639732  13.84193186]
3.140484712978569
[ -1.90710347 -18.89960509 -14.88848068  13.79188831  -7.17898173]
-7.991521960707387


array([None, None, None, None], dtype=object)

In [77]:
# 求一维数组去掉最大值和最小值之后的均值
def calcMean(row):
    # print(row)
    newRow = row[np.logical_and(row != row.max(), row != row.min())]
    rowMean = newRow.mean()
    # print(rowMean)
    return rowMean


# 求data2中每行去掉最大值和最小值之后的均值
np.apply_along_axis(calcMean, axis=1, arr=data2)

array([-2.69549052,  5.37656196,  3.14048471, -7.99152196])

In [79]:
# 求data2中每行去掉最大值和最小值之后的均值
np.apply_along_axis(
    lambda x: x[np.logical_and(x != x.max(), x != x.min())].mean(), axis=1, arr=data2
)

array([-2.69549052,  5.37656196,  3.14048471, -7.99152196])

In [81]:
# 0-10之间分成10等份
np.linspace(0, 10, 10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [82]:
# 1-10之间分成10等份
np.linspace(1, 10, 10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [83]:
# 0-1之间分成10等份
np.linspace(0, 1, 10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [84]:
data3 = np.random.randint(1,5,size=(3,5))
data3

array([[4, 2, 4, 4, 4],
       [3, 1, 2, 1, 3],
       [1, 2, 4, 3, 3]])

In [85]:
# 返回data3中的唯一值
np.unique(data3)

array([1, 2, 3, 4])

In [86]:
# 返回data3中的唯一值，统计每个值出现的次数
np.unique(data3, return_counts=True)

(array([1, 2, 3, 4]), array([3, 3, 4, 5]))